import { useEffect, useState } from 'react';
import { api } from '../lib/api';

type Call = { id: string; provider: string; direction: string; phone_number: string; status: string; started_at?: string | null; duration_seconds?: number | null; clients?: { client_name?: string | null } | null; sales_representatives?: { employee_code?: string | null; user_profiles?: { display_name?: string | null } | null } | null };
function dateLabel(value?: string | null) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }

export function CallsPage() {
  const [calls, setCalls] = useState<Call[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { setCalls((await api<{ data: Call[] }>('/telephony/calls')).data ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load call history.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  return <section className="page-panel"><div className="page-panel-heading"><div><p className="eyebrow">CALL OPERATIONS</p><h2>Calls & IVR</h2><p>Provider call history is linked to clients, representatives, and field visits.</p></div><button type="button" onClick={() => void load()} disabled={loading}>{loading ? 'Refreshing…' : 'Refresh'}</button></div><div className="integration-notice"><strong>IVR provider connection required</strong><p>This CRM is ready to receive verified call events, recordings, and outcomes from an approved telephony provider. No calls are placed from this screen until that provider is configured.</p></div>{error && <p className="error-message">{error}</p>}{loading ? <p>Loading call history…</p> : calls.length === 0 ? <div className="empty-state"><strong>No IVR calls recorded</strong><p>When the telephony provider is connected, inbound and outbound activity will appear here.</p></div> : <div className="data-table-wrap"><table><thead><tr><th>Client</th><th>Representative</th><th>Direction</th><th>Phone</th><th>Started</th><th>Duration</th><th>Status</th></tr></thead><tbody>{calls.map((call) => <tr key={call.id}><td>{call.clients?.client_name ?? '—'}</td><td>{call.sales_representatives?.user_profiles?.display_name ?? call.sales_representatives?.employee_code ?? '—'}</td><td>{call.direction}</td><td>{call.phone_number}</td><td>{dateLabel(call.started_at)}</td><td>{call.duration_seconds ? `${call.duration_seconds}s` : '—'}</td><td><span className={`status-badge status-${call.status}`}>{call.status}</span></td></tr>)}</tbody></table></div>}</section>;
}
