import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import './MasterDataPages.css';

type Contact = { id: string; name: string; designation?: string | null; is_primary: boolean };
type Assignment = { id: string; status: string; sales_representatives?: { employee_code: string; user_profiles?: { display_name?: string | null } | null } | null };
type Client = { id: string; client_name: string; client_code: string; client_type: string; status: 'active' | 'inactive'; priority: 'low' | 'normal' | 'high' | 'critical'; address?: string | null; city?: string | null; latitude?: number | null; longitude?: number | null; client_contacts?: Contact[]; sales_representative_client_assignments?: Assignment[] };
type ClientForm = { clientCode: string; clientName: string; clientType: string; priority: Client['priority']; status: Client['status'] };
const blank: ClientForm = { clientCode: '', clientName: '', clientType: 'School', priority: 'normal', status: 'active' };

export function ClientsPage() {
  const [items, setItems] = useState<Client[]>([]); const [form, setForm] = useState<ClientForm>(blank); const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState<'all' | Client['status']>('all'); const [filtersOpen, setFiltersOpen] = useState(false); const [editing, setEditing] = useState<Client | null>(null); const [viewing, setViewing] = useState<Client | null>(null); const [modal, setModal] = useState(false); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const clientTypes = useMemo(() => [...new Set(items.map((item) => item.client_type).filter(Boolean))].sort(), [items]);
  const filtered = items.filter((item) => (!type || item.client_type === type) && (status === 'all' || item.status === status));
  const load = async () => { try { setMessage(''); const query = new URLSearchParams(search.trim() ? { search: search.trim() } : {}); setItems((await api<{ data: Client[] }>(`/clients?${query}`)).data ?? []); } catch (e) { setMessage((e as Error).message); } };
  useEffect(() => { void load(); }, []);
  const openCreate = () => { setEditing(null); setForm(blank); setMessage(''); setModal(true); };
  const openEdit = (item: Client) => { setEditing(item); setForm({ clientCode: item.client_code, clientName: item.client_name, clientType: item.client_type, priority: item.priority, status: item.status }); setMessage(''); setModal(true); };
  const view = async (id: string) => { try { setViewing((await api<{ data: Client }>(`/clients/${id}`)).data); } catch (e) { setMessage((e as Error).message); } };
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); try { await api(editing ? `/clients/${editing.id}` : '/clients', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(form) }); setModal(false); setEditing(null); setMessage(editing ? 'Client updated successfully.' : 'Client created successfully.'); await load(); } catch (e) { setMessage((e as Error).message); } finally { setSaving(false); } }
  async function toggle(item: Client) { try { await api(`/clients/${item.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: item.status === 'active' ? 'inactive' : 'active' }) }); setMessage('Client status updated successfully.'); await load(); } catch (e) { setMessage((e as Error).message); } }
  const clearFilters = () => { setType(''); setStatus('all'); };
  return <section className="page-panel master-page"><div className="page-panel-heading"><div><p className="eyebrow">CLIENT DIRECTORY</p><h2>Clients</h2><p>Manage customer accounts used in field visits and sales orders.</p></div></div>
    <div className="master-toolbar"><div className="master-search"><input value={search} placeholder="Search client name or code" onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void load(); }} /><button className="quiet-button" type="button" onClick={() => void load()}>Search</button><button className="quiet-button" type="button" onClick={() => setFiltersOpen(!filtersOpen)}>Filters{type || status !== 'all' ? ' (active)' : ''}</button></div><button className="primary-action" type="button" onClick={openCreate}>+ Add client</button></div>
    {filtersOpen && <div className="master-filter-bar"><label>Client type<select value={type} onChange={(e) => setType(e.target.value)}><option value="">All client types</option>{clientTypes.map((value) => <option key={value}>{value}</option>)}</select></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button type="button" className="link-button" onClick={clearFilters} disabled={!type && status === 'all'}>Clear filters</button></div>}
    {message && <p role="status" className={message.includes('successfully') ? 'success' : 'error'}>{message}</p>}
    <div className="data-table-wrap"><table><thead><tr><th>Code</th><th>Client</th><th>Type</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td>{item.client_code}</td><td><strong>{item.client_name}</strong></td><td>{item.client_type}</td><td><span className={`priority priority-${item.priority}`}>{item.priority}</span></td><td><span className={`status-badge ${item.status}`}>{item.status}</span></td><td className="master-actions"><button type="button" className="icon-action" title="View client" aria-label={`View ${item.client_name}`} onClick={() => void view(item.id)}>◉</button><button type="button" className="icon-action" title="Edit client" aria-label={`Edit ${item.client_name}`} onClick={() => openEdit(item)}>✎</button><button type="button" className="icon-action" title={item.status === 'active' ? 'Deactivate client' : 'Activate client'} aria-label="Change client status" onClick={() => void toggle(item)}>{item.status === 'active' ? '⊘' : '✓'}</button></td></tr>)}{filtered.length === 0 && <tr><td colSpan={6} className="empty-row">No clients found.</td></tr>}</tbody></table></div>
    {modal && <div className="modal-backdrop" onMouseDown={() => !saving && setModal(false)}><div className="master-modal" role="dialog" aria-modal="true" aria-labelledby="client-modal-title" onMouseDown={(e) => e.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">CLIENT DIRECTORY</p><h3 id="client-modal-title">{editing ? 'Edit client' : 'Add client'}</h3></div><button className="icon-action" type="button" aria-label="Close" onClick={() => setModal(false)}>×</button></div><form className="master-modal-form" onSubmit={submit}><label>Client code<input required value={form.clientCode} onChange={(e) => setForm({ ...form, clientCode: e.target.value })} /></label><label>Client name<input required value={form.clientName} onChange={(e) => setForm({ ...form, clientName: e.target.value })} /></label><label>Client type<select value={form.clientType} onChange={(e) => setForm({ ...form, clientType: e.target.value })}>{[...new Set(['School', ...clientTypes])].map((value) => <option key={value}>{value}</option>)}</select></label><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as Client['priority'] })}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Client['status'] })}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="modal-actions"><button type="button" className="quiet-button" onClick={() => setModal(false)} disabled={saving}>Cancel</button><button className="primary-action" type="submit" disabled={saving}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Add client'}</button></div></form></div></div>}
    {viewing && <div className="modal-backdrop" onMouseDown={() => setViewing(null)}><div className="master-modal detail-panel" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">CLIENT PROFILE</p><h3>{viewing.client_name}</h3></div><button className="icon-action" type="button" aria-label="Close" onClick={() => setViewing(null)}>×</button></div><dl><dt>Client code</dt><dd>{viewing.client_code}</dd><dt>Type</dt><dd>{viewing.client_type}</dd><dt>Priority</dt><dd>{viewing.priority}</dd><dt>Status</dt><dd><span className={`status-badge ${viewing.status}`}>{viewing.status}</span></dd><dt>Location</dt><dd>{viewing.address || viewing.city || 'Not recorded'}</dd><dt>GPS</dt><dd>{viewing.latitude != null ? `${viewing.latitude}, ${viewing.longitude}` : 'Not recorded'}</dd><dt>Contacts</dt><dd>{viewing.client_contacts?.map((contact) => `${contact.name}${contact.is_primary ? ' (primary)' : ''}`).join(', ') || 'None'}</dd><dt>Assigned representatives</dt><dd>{viewing.sales_representative_client_assignments?.map((assignment) => assignment.sales_representatives?.user_profiles?.display_name ?? assignment.sales_representatives?.employee_code).join(', ') || 'None'}</dd></dl></div></div>}
  </section>;
}
