import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import './DashboardPage.css';

type RecentVisit = { id: string; status: string; check_in_time: string; outcome?: string | null; clients?: { client_name?: string } | null; sales_representatives?: { employee_code?: string; user_profiles?: { display_name?: string | null } | null } | null };
type Data = { totalClients: number; totalRepresentatives: number; activeRepresentatives: number; visitsToday: number; completedVisitsToday: number; activeVisits: number; ordersToday: number; salesToday: number; collectionsToday: number; recentVisits: RecentVisit[] };
type LiveVisit = { id: string; check_in_time: string; check_in_lat: number; check_in_lng: number; clients?: { client_name?: string } | null; sales_representatives?: { employee_code?: string; user_profiles?: { display_name?: string | null } | null } | null; latest_ping?: { latitude: number; longitude: number } | null };
const empty: Data = { totalClients: 0, totalRepresentatives: 0, activeRepresentatives: 0, visitsToday: 0, completedVisitsToday: 0, activeVisits: 0, ordersToday: 0, salesToday: 0, collectionsToday: 0, recentVisits: [] };
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

export function DashboardPage() {
  const [data, setData] = useState<Data>(empty); const [live, setLive] = useState<LiveVisit[]>([]); const [error, setError] = useState('');
  useEffect(() => { const load = () => void Promise.all([api<{ data: Data }>('/dashboard'), api<{ data: LiveVisit[] }>('/field-visits/live')]).then(([dashboard, activity]) => { setData({ ...empty, ...dashboard.data }); setLive(activity.data); setError(''); }).catch((reason) => setError((reason as Error).message)); load(); const timer = window.setInterval(load, 20000); return () => window.clearInterval(timer); }, []);
  const metrics = [['Visits today', data.visitsToday, `${data.completedVisitsToday} completed`], ['Active field visits', live.length, live.length ? 'GPS reporting active' : 'No one checked in'], ['Orders today', data.ordersToday, money(data.salesToday)], ['Collections today', money(data.collectionsToday), 'Recorded receipts']];
  return <>
    <section className="ops-hero"><div><p className="eyebrow">FIELD SALES COMMAND CENTER</p><h2>Know what your team is doing in the field—right now.</h2><p>Live visits, customer activity, orders, and collections in one operations view.</p></div><div className="ops-date"><span>Today</span><strong>{new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date())}</strong><small>{data.activeRepresentatives} active representatives</small></div></section>
    {error ? <section className="access-card"><h2>Dashboard data is unavailable</h2><p>{error}</p></section> : <>
      <div className="ops-metrics">{metrics.map(([label, value, note], index) => <section className={`ops-metric tone-${index}`} key={String(label)}><p>{label}</p><strong>{value}</strong><small>{note}</small></section>)}</div>
      <div className="ops-grid"><section className="ops-panel"><header><div><p className="eyebrow">LIVE FIELD ACTIVITY</p><h2>Team currently in the field</h2></div><span>Live · 20 sec</span></header>{live.length ? <div className="live-list">{live.map((visit) => { const name = visit.sales_representatives?.user_profiles?.display_name ?? visit.sales_representatives?.employee_code ?? 'Sales representative'; const lat = visit.latest_ping?.latitude ?? visit.check_in_lat; const lng = visit.latest_ping?.longitude ?? visit.check_in_lng; return <article key={visit.id}><i /><div><strong>{name}</strong><p>On visit · {visit.clients?.client_name ?? 'Unlisted client'}</p></div><time>{new Date(visit.check_in_time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${lat},${lng}`}>Map</a></article>; })}</div> : <div className="ops-empty"><strong>No active field visits</strong><p>When a representative checks in, their visit and last known location will appear here.</p></div>}</section>
      <section className="ops-readiness"><p className="eyebrow">OPERATIONS READINESS</p><h2>Get the field workflow live</h2><div><span className={data.totalRepresentatives ? 'done' : ''}>{data.totalRepresentatives ? '✓' : '○'}</span><p><strong>Create representatives</strong><small>{data.totalRepresentatives ? `${data.totalRepresentatives} representatives configured` : 'Add your field team'}</small></p></div><div><span>{data.visitsToday ? '✓' : '○'}</span><p><strong>Start GPS-verified visits</strong><small>{data.visitsToday ? `${data.visitsToday} visits recorded today` : 'Use a representative account to check in'}</small></p></div><div><span>{data.ordersToday ? '✓' : '○'}</span><p><strong>Create visit-based orders</strong><small>{data.ordersToday ? `${data.ordersToday} orders recorded today` : 'Add products, then create an order from a visit'}</small></p></div></section></div>
      <div className="ops-grid"><section className="ops-panel"><header><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Visit timeline</h2></div></header>{data.recentVisits.length ? <div className="timeline">{data.recentVisits.map((visit) => <article key={visit.id}><i className={visit.status} /><div><strong>{visit.sales_representatives?.user_profiles?.display_name ?? visit.sales_representatives?.employee_code ?? 'Representative'} {visit.status === 'checked_out' ? 'completed a visit' : 'checked in'}</strong><p>{visit.clients?.client_name ?? 'Unlisted client'}{visit.outcome ? ` · ${visit.outcome.replace('_', ' ')}` : ''}</p></div><time>{new Date(visit.check_in_time).toLocaleString()}</time></article>)}</div> : <div className="ops-empty"><strong>No visits recorded yet</strong><p>Assign a client to a representative, then start the first GPS visit.</p></div>}</section><section className="sales-today"><p className="eyebrow">TODAY'S SALES</p><h2>{money(data.salesToday)}</h2><p>{data.ordersToday} confirmed order(s) recorded today.</p><div><span>Visits completed</span><b>{data.completedVisitsToday} / {data.visitsToday}</b></div><div><span>Collections recorded</span><b>{money(data.collectionsToday)}</b></div></section></div>
    </>}
  </>;
}
