import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { supabase } from '../lib/supabase';
import { useIndustry } from '../industry/IndustryContext';
import { useCurrentMembership } from '../auth/useCurrentMembership';

type Industry = { id: string; code: string; name: string };
type Template = { logo_url: string | null; subject: string; body: string; footer: string | null };
const defaults: Template = { logo_url: null, subject: 'Quotation {{quotation_no}} from {{company_name}}', body: '<h2>Quotation {{quotation_no}}</h2><p>Dear {{client_name}},</p><p>Your quotation total is {{total}} and is valid until {{valid_until}}.</p>', footer: '<p>Thank you,<br>{{company_name}}</p>' };
const organizationId = import.meta.env.VITE_ORGANIZATION_ID;

export function QuotationEmailSettings() {
  const { activeIndustry } = useIndustry(); const { lockedIndustryTypeId } = useCurrentMembership();
  const [industryId, setIndustryId] = useState<string>(''); const [template, setTemplate] = useState<Template>(defaults); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api<{ data: Industry[] }>('/industry-types?status=active').then(({ data }) => { const selected = lockedIndustryTypeId ?? data.find((item) => item.code.toLowerCase() === activeIndustry)?.id ?? ''; setIndustryId(selected); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Unable to load industries.')); }, [activeIndustry, lockedIndustryTypeId]);
  useEffect(() => { if (!industryId) return; api<{ data: Template | null }>(`/settings/quotation-email-template?industryTypeId=${encodeURIComponent(industryId)}`).then(({ data }) => setTemplate(data ?? defaults)).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Unable to load template.')); }, [industryId]);
  async function uploadLogo(file: File) { if (!supabase || !organizationId) return setMessage('Supabase and organization configuration are required for logo upload.'); setSaving(true); try { const path = `${organizationId}/${industryId}/${crypto.randomUUID()}-${file.name}`; const { error } = await supabase.storage.from('quotation-email-logos').upload(path, file, { upsert: false }); if (error) throw error; const { data } = supabase.storage.from('quotation-email-logos').getPublicUrl(path); setTemplate((current) => ({ ...current, logo_url: data.publicUrl })); } catch (error) { setMessage(error instanceof Error ? error.message : 'Logo upload failed.'); } finally { setSaving(false); } }
  async function save() { if (!industryId) return; setSaving(true); setMessage(''); try { await api('/settings/quotation-email-template', { method: 'PUT', body: JSON.stringify({ industryTypeId: industryId, logoUrl: template.logo_url, subject: template.subject, body: template.body, footer: template.footer }) }); setMessage('Quotation email template saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save template.'); } finally { setSaving(false); } }
  return <section className="settings-section"><div className="settings-section-heading"><h3>Quotation email template</h3><p>Use <code>{'{{client_name}}'}</code>, <code>{'{{quotation_no}}'}</code>, <code>{'{{total}}'}</code>, <code>{'{{valid_until}}'}</code>, and <code>{'{{company_name}}'}</code>.</p></div>{template.logo_url && <img src={template.logo_url} alt="Email logo preview" style={{ maxHeight: 64, maxWidth: 220 }} />}<label>Logo<input type="file" accept="image/*" disabled={saving || !industryId} onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadLogo(file); }} /></label><label>Subject<input value={template.subject} onChange={(event) => setTemplate({ ...template, subject: event.target.value })} /></label><label>Body (HTML supported)<textarea rows={9} value={template.body} onChange={(event) => setTemplate({ ...template, body: event.target.value })} /></label><label>Footer (HTML supported)<textarea rows={4} value={template.footer ?? ''} onChange={(event) => setTemplate({ ...template, footer: event.target.value || null })} /></label><div className="settings-preview"><strong>Preview</strong><div dangerouslySetInnerHTML={{ __html: template.body.replace(/{{client_name}}/g, 'Client name').replace(/{{quotation_no}}/g, 'QT-0001').replace(/{{total}}/g, 'INR 1,000.00').replace(/{{valid_until}}/g, '31 Dec 2026').replace(/{{company_name}}/g, 'Your company') }} /></div>{message && <p>{message}</p>}<button type="button" className="settings-save-btn" disabled={saving || !industryId} onClick={() => void save()}>{saving ? 'Saving…' : 'Save quotation email template'}</button></section>;
}
