import { Router } from 'express'; import { followUps } from '../controllers/follow-ups.controller.js'; import { authenticate } from '../middleware/authenticate.js'; import { requireRoles } from '../middleware/authorize.js';
export const followUpsRouter = Router();
followUpsRouter.post('/field-visits/:id/follow-ups', authenticate, requireRoles('sales_representative'), followUps.createFromVisit);
followUpsRouter.get('/follow-ups/mine', authenticate, requireRoles('sales_representative'), followUps.mine);
followUpsRouter.get('/follow-ups', authenticate, requireRoles('super_admin', 'admin', 'sales_manager'), followUps.all);
followUpsRouter.post('/follow-ups', authenticate, requireRoles('super_admin', 'admin', 'sales_manager'), followUps.createManual);
followUpsRouter.patch('/follow-ups/:id', authenticate, requireRoles('super_admin', 'admin', 'sales_manager'), followUps.update);
followUpsRouter.patch('/follow-ups/:id/reschedule', authenticate, requireRoles('super_admin', 'admin', 'sales_manager'), followUps.reschedule);
followUpsRouter.get('/follow-ups/:id/history', authenticate, requireRoles('super_admin', 'admin', 'sales_manager'), followUps.history);
followUpsRouter.post('/orders/:id/follow-ups', authenticate, requireRoles('super_admin', 'admin', 'sales_manager'), followUps.createForOrder);
followUpsRouter.patch('/follow-ups/mine/:id', authenticate, requireRoles('sales_representative'), followUps.updateMine);
followUpsRouter.patch('/follow-ups/mine/:id/reschedule', authenticate, requireRoles('sales_representative'), followUps.rescheduleMine);